### ISSUE TITLE
Roadmap - v1.5

### ISSUE THREAD

**Issue by seripap** [seripap/darkwire.io#5]
- [x] Encrypted File Transfer
- [x] Tests
- [x] Custom Handles/Slash commands
- [ ] ~~Option to hide " ... is typing " on either clients~~*
- [x] Support for Symbols + Emojis
- [ ] ~~Remove Vendor Files~~*

*Removed from v1.5

**Comment by seripap** [comment]
Since v1.5 was a heavier update than expected, we are going to backlog some features and cleanup that were planned.

**Comment by dietmarw** [comment]
For future releases, why not simply use GH's milestones. You can the move around the tickets.

**Comment by seripap** [comment]
Yeah, i'll probably just create them and start closing out tickets

**Comment by dietmarw** [comment]
This looks somewhat strange. But perhaps you have something different in mind. You would not create a milestone per ticket but one milestone, e.g., v1.5.0 and then assign the different tickets to it. And the v1.6.0 etc 
But maybe you got your reasons for having duplicate version milestones  :-)

**Comment by seripap** [comment]
That actually makes more sense. Onwards!
